# Generated by Django 4.2.2 on 2023-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='유저')),
                ('word_id', models.IntegerField(verbose_name='단어')),
            ],
        ),
    ]
