# Generated by Django 4.2.2 on 2023-06-10 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 22, 47, 23, 566868), verbose_name='작성일시'),
        ),
        migrations.AddField(
            model_name='notice',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='작성자'),
        ),
    ]
