# Generated by Django 4.2.2 on 2023-06-11 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_createtime_notice_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='user_id',
        ),
        migrations.AddField(
            model_name='notice',
            name='uid',
            field=models.IntegerField(default=1, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 11, 23, 12, 339807), verbose_name='작성일시'),
        ),
    ]
