# Generated by Django 4.2.2 on 2023-06-11 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_remove_notice_user_id_notice_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 11, 23, 36, 890138), verbose_name='작성일시'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='uid',
            field=models.CharField(max_length=255, verbose_name='작성자'),
        ),
    ]
