# Generated by Django 4.2.2 on 2023-06-11 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_notice_createtime_alter_notice_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 13, 15, 44, 772374), verbose_name='작성일시'),
        ),
    ]
