# Generated by Django 4.2.2 on 2023-06-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255, unique=True, verbose_name='계정')),
                ('pw', models.CharField(max_length=255, verbose_name='비밀번호')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
